# ref link: https://alinex.gitlab.io/env/mkdocs/
# Site Information
site_name: Gtz4All
site_url: https://gtz4all.github.io/
site_description: Gtz4All Reference Documentation
#site_author: Gtz4All
copyright: "Copyright 2022 <a href='https://gtz4all.github.io'>Gtz4All</a>. All Rights Reserved." 

nav:
  - Home:
    - Home: "index.md"
    - Welcome: "welcome.md"
    - Cloud: "cloud/introduction.md"
    - Networking: "networking/introduction.md"
    - License: "license.md"

  - Cloud: 
    - Introduction: "cloud/introduction.md"
    - AWS:
      - Introduction: "cloud/aws/introduction.md"
    - GCP:
      - Introduction: "cloud/gcp/introduction.md"
    - Azure:
      - Introduction: "cloud/azure/introduction.md"

  - Networking: 
    - Introduction: "networking/introduction.md"
    - Arista:
      - Introduction: "networking/arista/introduction.md"
    - Cisco:
      - Introduction: "networking/cisco/introduction.md"

  - DevOps: 
    - Introduction: "devops/introduction.md"
    - Terraform:
      - Introduction: "devops/terraform/introduction.md"
    - Ansible:
      - Introduction: "devops/ansible/introduction.md"
    - Python:
      - Introduction: "devops/python/introduction.md"

  - Contact Us:
      - Contribute: "contact-us/contribute.md"
      - FAQs: "contact-us/faqs.md"
      - Contact Us: "contact-us/contact-me.md"

# Material Mkdocs Theme + Extras
theme:
  name: material
  custom_dir: docs/assets/overrides
  icon: # https://www.materialpalette.com/icons
    logo: material/book-open-page-variant
  favicon: material/book-open-page-variant #assets/images/logos/favicon.ico
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - navigation.tabs
    - navigation.instant
    - header.autohide

  palette: # https://www.materialpalette.com/colors
    - scheme: default
      accent: deep purple
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      accent: teal
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

  include_sidebar: true

extra:
  social:
    - icon: material/home
      link: 'https://gtz4all.github.io/'
    - icon: material/github
      link: 'https://github.com/gtz4all'

extra_css:
  - assets/extra.css

# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:materialx.emoji.to_svg
      emoji_index: !!python/name:materialx.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
